database:
  host: localhost # host of database
  port: 5432 # default port for PostgreSQL
  database: postgres # name of database. A database server can contain multiple databases
  user: shrigorevich
  password: strongpass
  poolSize: 8

mob_spawn:
  regular_spawn_interval: 45 # sec
  #not loaded
  wave_spawn_interval: 600 # sec

#not loaded
enemy_power:
  regular_number_players_factor: 1.0 # PlayersCountMultiplier for Number of single spawned mobs
  days_factor: 1.0 # DaysCountMultiplier

