database:
  host: localhost # host of database
  port: 5432 # default port for PostgreSQL
  database: postgres # name of database. A database server can contain multiple databases
  user: shrigorevich
  password: strongpass
  poolSize: 8

mob_spawn:
  max_qty: 70
  regular_spawn_interval: 45 # sec
  #not loaded
  wave_spawn_interval: 600 # sec

#not loaded
enemy_power:
  players_factor: 2.0 # PlayersCountMultiplier for spawned mobs power
  days_factor: 1.0 # DaysCountMultiplier

