database:
  host: localhost # host of database
  port: 5432 # default port for PostgreSQL
  database: postgres # name of database. A database server can contain multiple databases
  user: shrigorevich
  password: strongpass
  poolSize: 8

mob_spawn:
  max_mob_qty: 70
  pressure_interval: 45 # sec
  wave_interval: 600 # sec
  pressure_players_factor: 4.0 # PlayersCountMultiplier for spawned mobs power
  wave_players_factor: 4.0
