name: Ml
version: '${project.version}'
main: org.shrigorevich.ml.Ml
api-version: 1.19
commands:
  struct:
    description: "Structure management"
    aliases: [ s ]
    usage: "/<command> create | c [type] [name] [isDestructible] \n 
            /<command> save_volume | sv [volumeName] \n
            /<command> apply_volume | av [structId] [volumeId]"
  npc:
    description: "Npc management"
    usage: "/<command> create \n
            /<command> clear"


